name: lzstring
version: 2.0.0+2
description: Dart implementation of lz-string compression algorithm. Originally written in JavaScript, for more details, please refer to http://pieroxy.net/blog/pages/lz-string/index.html
homepage: https://github.com/skipness/lzstring-dart
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  typed_data: "^1.3.0"
dev_dependencies:
  test: ^1.17.5
